dist: focal
cache: ccache
language: cpp

os: linux
arch: arm64

install: skip

script:
- sed -i 's/# deb-src/deb-src/g' /etc/apt/sources.list
- cat /etc/apt/sources.list
- INSTALLDEPS=debian ./pbp-install-libva

notifications:
  email: false
